<?php

// Opgelet: om errors te vermijden - waar je zelf de schuld aan heeft - werd de code geschreven met 
// 'enkele aanhalings tekens (voorbeemd: href='http://www.google.com') binnen de dubbele aabhaling tekens
// voorbeeld define('COMMUNIQUE',"HTML code en <font color='red'>in rood</font>");)
define('COMMUNIQUE1',"<div align='center'><b>NEED MONEY ?</b><br><a href='affiliation.php'>AFFILIATION <u>HERE</u></a><br> and receive <span class='fontrouge'><b>".$affiliateCom."%</b></span> on the sales generated by visitors coming from your website.</div>");
define('COMMUNIQUE2',"<div align='center'><b>Secured Payment<br>Pay in all confidence</b><br><img src='im/payment.gif'><br></div>");
define('COMMUNIQUE3',"<div align='center'><b>NEED AN ADVICE ?</b><br>CALL US TO:<br><div class='fontrouge'><b>Tel: ".$tel."</b></div><div><b>OR</b><br><a href='infos.php?info=5'><u>Click HERE</u></a></div></div>");

define('MEILLEURES_VENTES',"Some of ours best sales");
define('LAST_NEWS',"Some of ours last news");
define('FEW_PRODUCTS',"Some items sold here...");
define('EN_PROMO',"Some of ours specials sold here...");
define('EN_EXCLUSIVITE',"Our exclusive ... selection !");
define('DIX_MEILLEURES_VENTES',"Our 10 best sales");
define('PAS_DE_PRODUITS_DANS_CETTE_CATEGORIE','-- No products in this category ---');
define('PAS_DE_PROMOTIONS_DANS_CETTE_CATEGORIE','No specials in this category');
define('PAS_DE_NOUVEAUTES_DANS_CETTE_CATEGORIE','No new products in this category');
define('QUELQUES_UN_DES_PLUS_RECENTS_ARTICLES','Some of the most recent articles.');
define('PROMOTION','*** SPECIALS ***');
define('REF','O/Ref');
define('BIENVENU_SUR','Welcome to ');
define('MENU_RAPIDE','Quick menu');
define('MENU_RAPIDE2','By categories');
define('MENU_RAPIDE3','By companies');
define('TOUTES_MARQUES','All companies');
define('TOUTES_CAT','By products');
define('AUTRES','Others');
define('NOUVEAUTES','News');
define('NOUVEAUTESMAJ','NEWS');
define('PROMOTIONS','Specials');
define('COMMENTAIRES','Comments');
define('PRODUITS','Products');
define('LIVRAISON','Shipping');
define('TOTAL','Total');
define('VOUS_N_AVEZ_PAS_D_ARTICLES_DANS_VOTRE_CADDIE','-- Your Shopping Cart is currently empty! --');
define('ARTICLES','Items');
define('ARTICLE','Item');
define('PRIX','Price');
define('PRIXEN','Prices');
define('PRIX_UNITAIRE','U.P.');
define('QTE','Qty');
define('COMMANDER','Order');
define('TVA','TVA');
define('PRIX_HT','Price ET');
define('SOUS_TOTAL','Sub-total');
define('TOTAL_POIDS','Total weight');
define('TAXE','Tax');
define('TOTAL_TAXE','Total tax');
define('MONTANT_A_PAYER','To pay');
define('VOICI_QUELQUES_PRODUITS_DANS_CETTE_CATEGORIE','Here some products from this category ...');
define('VOICI_QUELQUES_PRODUITS_DANS_CETTE_CATEGORIE2','Here some products from this sub category ...');
define('CET_ARTICLE_EST_PRESENT_DANS_VOTRE_CADDIE','This item is in your cart');
define('CET_ARTICLE_N_EST_PAS_PRESENT_DANS_VOTRE_CADDIE','This item is not in your shopping cart');
define('A_ETE_AJOUTE_DANS_VOTRE_CADDIE','Added in your shopping cart');
define('A_ETE_SUPPRIME_DE_VOTRE_CADDIE','Removed from your shopping cart');
define('AJOUTER_AU_CADDIE','Add to cart');
define('RETIRER_DU_CADDIE','Remove from cart');
define('NON','No');
define('OUI','Yes');
define('POIDS','Weight');
define('EN_PROMOTION_JUSQU_AU','Offer until');
define('FIN_DE_PROMOTION_DANS','End of offer in');
define('JOURS','Day');
define('SOIT','Or');
define('EN_PROMOTION_JUSQUE_A_NOUVEL_ORDRE','In special until new order');
define('VOIR_LA_LISTE_DES','See list of');
define('EN_STOCK','In stock');
define('NOT_IN_STOCK','Order on hand');
define('IN_ORDER_MESSAGE','Available within 8 days.');
define('PAGE','Page');
define('DE','From');
define('A','to');
define('TOUTES','All');
define('TOUT','All');
define('IMAGE','Image');
define('ARTICLE_TAXABLE','Tax');
define('ARTICLE_TELE','Download');
define('CLASSER_PAR','Sort by');
define('CLASSER_PAR2','Sorted by');
define('ARTICLE_PRESENT_DANS_LE_CADDIE','Item IN your shopping cart');
define('ARTICLE_ABSENT_DU_CADDIE','Item IS NOT in your shopping cart');
define('LIVRAISON_GRATUITE','FREE SHIPPING');
define('D_ACHAT_HORS_TAXE','of purchase ET');
define('D_ACHAT_TTC','of purchase including taxes');
define('ACHAT_SUR',"purchase <b>$store_name</b>");
define('ACHAT_SUR_DOMAINE',"purchase <b>".$domaineFull."</b>");
define('REMISE_DE','<B>SAVE</B>');
define('REMISE','Save');
define('REMISE_SUR_COMMANDES','Discount on previous purchases');
define('POUR','for');
define('RECHERCHER','Search');

// panier
define('VOTRE_CADDIE','My cart');
define('RECUPERER_CADDIE','Save/Get cart');
define('ENREGISTRER_CADDIE','Save my cart');
define('VIDER_CADDIE','Empty cart');
define('DEVISE','Currency');
define('TELECHARGER','Download');
define('CADDIE_VIDE','Empty cart');
define('MOT_DE_PASSE','password');
define('METTRE_A_JOUR_LE_CADDIE','Update cart');
define('CADDIE_MIS_A_JOUR','Cart updated');
define('ENLEVER_1_ITEM_AU_CADDIE','1 item less');
define('AJOUTER_1_ITEM_AU_CADDIE','1 item more');
define('SUPPRIMER_L_ARTICLE_REF','Remove from cart');
define('DANS_LE_CADDIE','In the cart');
define('VISUALISE_FACTURE','Invoice preview');
define('SELECTIONNE_PAYS','Select country');
define('AUX_ABONNES_DE_LA_NEWSLETTER','Today');
define('VEUILLEZ_SAISIR_VOTRE_CODE','Expiry date:');
define('SEUIL_DE_LA_COMMANDE','Minimum purchase');
define('AVANT_TAXE','before tax');
define('ACTIVE','Activate');
define('COUPON_CODE','Discount code');
define('CODE_ERRONE','Bad code!');
define('BRAVO','Bingo!');
define('DATE_DEPASSE','Out of date!');
// INFORMATIONS
define('UTILISATION_CADDIE','Using cart');
define('PAIEMENTS','Payments');
define('EXPEDITIONS_ET_RETOURS','Shipping & returns');
define('IMPRIMER_CATALOGUE','Print Catalog');
define('EXPEDITIONS_ET_RETOURS_MAJ','SHIPPING & RETURNS');
define('CONDITIONS_D_USAGE','Conditions of sales');
define('NOUS_CONTACTER','Contact us');
define('CONDITIONS_DE_VENTE','User agreement');
		define('LINK1','Outside link');
// converter
define('CONVERTIR','Convert');
define('HOME','Home');
define('LIVRAISON_NON_INCLUSE','Shipping not included');
define('TAXE_INCLUSE','Tax included');
define('TAXE_NON_INCLUSE','Tax not include');
define('PAS_DE_TAXE','No tax');
// formulaire
define('FORMULAIRE_D_EXPEDITION','ORDER FORM');
define('VOUS','You');
define('CIVILITE','Gender');
define('M','M.');
define('MME','Ms.');
define('NOM','Name');
define('PRENOM','Firstname');
define('ADRESSE_EMAIL','E-mail address');
define('ADRESSE','Address');
define('CODE_POSTAL','ZIP code');
define('VOTRE_ADRESSE_D_EXPEDITION','Shipping address');
define('VOTRE_ADRESSE_DE_FACTURATION22','<b>Billing address</b>');
define('COMPAGNIE22','Firstname, Lastname');
define('VILLE','City');
define('PAYS','Country');
define('PROVINCE','Province');
define('VOS_INFORMATIONS_PERSONNELLE','<b>Contact infos</b> <i>(Just in case...)</i>');
define('NUMERO_DE_TELEPHONE','Phone number');
define('SI_VOUS_AVEZ_DES_COMMENTAIRES','Comments');
define('VOTRE_COMMANDE','Your order');
define('SELECTIONNER_UN_MODE_DE_PAIEMENT','Select payment');
define('CARTE_DE_CREDIT','Credit card');
define('CHEQUE_OU_TRANSFERT_BANCAIRE_OU_MANDAT_POSTAL','Payment by');
define('CONTINUER','Proceed');
define('CHAMPS_OBLIGATOIRES','Fields necessary');
define('HT','Net');
define('VEUILLEZ_SELECTIONNER','Please select');
define('VEUILLEZ_PRENDRE_CONNAISSANCE','Please read conditions of sales.');
define('AI_LU','I have read and accepted the conditions of sales :');
define('SAVE_INFO','Save the shipping address :');
define('BIENVENU2','Welcome');
define('COMPTE_NON_VALIDE','Account not valid !');
define('VEUILLEZ_SAISIT_VOTRE_MOT_DE_PASSE','Plaease enter a password !');
define('VOUS_ETES_ENREGISTRE_ET_VOTRE_MOT_DE_PASSE_EST','Get the shipping adress saved in a previous purchase :');
define('POUR_PLUS_DINFORMATIONS','For more information please contact us to');
define('VOTRE_COMPTE','Your account');
define('LE','on');
// CONTACTEZ NOUS
define('MESSAGE','Message');
define('REMPLICEZ_CE_FORMULAIRE','Fill the following form to comunicate with us..<BR>Fields with an asterisk (*) are necessary.');
define('ENVOYER','Send');
define('ANNULER','Reset');
define('VEUILLEZ_LAISSER_UN_MESSAGE','Please, leave a message');
define('CHAMPS_NON_VALIDE','Fiels not valid:');
define('VOTRE_COURRIER_A_ETE_ENVOYE_AVEC_SUCCES','Your message has been sent successfuly');
define('NREF','O.Ref');
// bewaar_winkelmandje.php
define('NOM_DU_CADDIE','Cart Name');
define('VOTRE','Your');
define('ACTUALISER','Update');
define('SUPPRIMER','Delete');
define('FERMER','Close');
define('NUMERO_DE_PANIER','Cart Number');
define('VEUILLEZ_ENTRER_UN','Please enter a');
define('ET_VOTRE','and the');
define('ENREGISTRER_RECUPERER_CADDIE','Save/Get cart');
define('ENREGISTRER_RECUPERER_CADDIE_MAJ','SAVE & GET CART');
define('MOT_DE_PASSE_NON_IDENTIQUE','Cart names not equal.<br>Please start again.<br>Thank you.');
define('VEUIILEZ_SELECTIONNER_AU_MOINS_1_ARTICLE','<b>Your cart is empty.</b><br>To save your cart, select at least 1 item.<br>Thank you.');
define('MOT_DE_PASSE_DEJA_UTILISE','Cart name already registered, please start again.<br>Thank you.');
define('CADDIE_ENREGISTRE_AVEC_SUCCES','CART SAVED SUCCESSFULY');
define('CONFIRMEZ_MOT_DE_PASSE','Confirm Cart Name');
define('VOTRE_CADDIE_N_EST_PAS_ENREGISTRE_OU','Your cart is not registered <b>OR</b> your cart has been saved more than '.$saveCart.' days ago.<br>Please start again or save your cart again.');
define('CADDIE_RECUPERE_ET_ACTUALISE','<b>CART ECOVERED AND UPDATED SUCCESSFULY.</b><br>You can continue your shopping.');
define('VEUILLEZ_SAISIR_VOTRE_MOT','Please, enter your password and your cart number');
define('TEXT_SAVECART_1',"<div><b>TO SAVE YOUR CART</b></div><ul><li>Once recorded, we keep your items in our database and you will be able to get them back for a <b>".$saveCart." days period</b>.<br><b>Never you have to consider saving cart as a reservation</b>.</li><li>At the end of this period, you will lose the contents of your cart. You will have to save it again.</li><li>After to have entered your cart name, We will give you a cart number sent on your <b>email</b></li><li>Please keep your <b>cart name</b> and your <b>cart number</b> in order to get back your cart.</li><li>You can save carts as much than you want.</li></ul>");
define('TEXT_SAVECART_2',"<div><b>TO RECOVER YOUR CART</b></div><ul><li>Your cart is saved in our database for a <b>".$saveCart." days period.</b> </li><li>At the end of this period, you will lose the contents of your cart. You will have to save it again.</li><li><u>The recovered cart will erase the contents of the current cart.</u></li><li>Once your cart recovered, you will be able to continue your shopping in a normal way.</li><li>
If you wish to save your cart again, click the button ' Update' in 'Your cart' module.<br><b>Each update will extend the ".$saveCart." days period for 15 days more.</b></li><li>Prices and offers of recovered items in the recovered cart will be adjusted automatically.</li></ul>");
define('TEXT_SAVECART_3',"<b>* $store_company</b> is allowed to change price, tax rate or sp�cifiaction of any item included in your cart.
<br><b>**</b> Saving your cart not guaranteed the availability, the price or the offer of the saved items.");
define('CADDIE_ID','CART');
define('BONJOUR','Hi');
define('VOUS_VENEZ_DE_SAUVEGARDER_UN_CADDIE','You have saved a cart in');
define('VOTRE_NOM_DE_CADDIE_EST','Your cart name is');
define('VOTRE_NUMERO_DE_CADDIE_EST','Your Cart Number is');
define('VOTRE_CADDIE_SUR','Your cart in');
// SEARCH
define('MODE_EMPLOI','How to use it');
define('AIDE',"<b>The search is done on the name, description, reference, supplier, manufacturer, note, waranty and EAN (European Article Numbering).</b><br><br>
								  <u>All words</u><br>
                                  Example : toto titi => Search all products containing \"toto\" <b>AND</b> \"titi\".<br><br>
								  <u>Any word</u><br>
                                  Example : toto titi => Search all products containing \"toto\" <b>OR</b> \"titi\".<br><br>
								  <u>Exact sentence</u><br>
                                  Example : toto titi => Search all products containing \"toto titi\".<br><br>
            <b>AND</b> or \"All words\" is the default operator.<br>
            Accents and Uppercases are not considered.");
define('RESULTAT_DE_LA_RECHERCHE','Searching result');
define('RECHERCHE_NON_DEFINIE','<b>Search field is empty</b>.<br>Try again.');
define('AUCUN_RESULTAT','No products have been found for this search');
define('RESULTAT','Results found');
// top 10
define('NON_DISPONIBLE','Not available');
define('GRIS','Gray');
define('ROSE','Pink');
define('NOIR','Black');
define('JAUNE','Yellow');
define('BLANC','White');
define('BLEU','Blue');
define('PERSO',AUTRES);
define('CATEGORIE','Category');
define('ACHETER','Buy');
define('FOURNISSEUR','Supplier');
define('COMPAGNIE','<b>Manufacturer</b>:');
define('COMPAGNIE2','Company');
define('LES_PLUS_VISITES','The most viewed');
define('PRODUITS_DANS_CETTE_CATEGORIE','items in this category');
define('VOIR_ARTICLES_DE_LA_CATEGOIRE','See items in the category');
define('DESCRIPTION','Description');
define('DESCRIPTIONMAJ',"DESCRIPTION");
define('VOIR_OPTIONS','Select options');
define('PRODUIT_OPTIONS','Attributes');
define('LIRE_CONDITIONS','Read conditions');
define('FREE_SHIPPING_COUNTRIES','Free shipping countries');
define('PRODUITS_AFFILIES','CUSTOMERS WHO BOUGHT THIS PRODUCT ALSO PURCHASED');
// select payment page
define('PAIEMENT','Payment');
define('PAYPAL_EST_UN_COMPTE_BANCAIRE',"Paypal is a virtual bank account which allows you to pay and receive payments by email. The payment with <a href=\"http://www.paypal.com\" target=\"_blank\">Paypal</a> is full secured. If you do not have an account, you can open one or pay with your credit card.");
define('UNE_FOIS_VOTRE_PAIEMENT_CONFIRME',"
(1)&nbsp;As soon as your payment confirmation you will receive and email with your Order Id Number (NIC), your Client Number and the URL of your <b>Customer Interface</b>(*) accessible with your NIC.<br>Your puchase will be processed for shipping.<br><br>
(2)&nbsp;After your have selected your payment, your purchase will be saved and we will sent you and email with your Order Id Number (NIC), your Client Number and the URL of your <b>Customer Interface</b>(*) accessible with your NIC.<br>As soon as your payment received, your puchase will be processed for shipping.<br><br>
 (*)&nbsp;<u>Through your Customer Interface you can</u>:<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Confirm the payment you have selected (**).<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Read our bank or postal informations (**).<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Check your payment (received | not received).<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Check your order (shipped yes | no).<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Download your order.<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Print or/and receive your invoice.<br>
 <img src=\"im/fleche_right.gif\">&nbsp;Subscribe or unsubscribe to our Newsletter.<br><br>
 (**) If payment by cheque, bank tansfert or money order.");
define('LE_PAIEMENT_PAR_CARTE_DE_CREDIT',"The payment by credit card is full secured and is processed through the secure payment server of");
define('LE_MONTANT_ENVOYE_DOIT_ETRE',"The amount must be payed in");
define('LE_MONTANT_ENVOYE_DOIT_ETRE2',"Amount to send:");
define('SELECTIONNER_MODE_DE_PAIEMENT','Select payment');
define('CHEQUE_BANCAIRE','Cheque');
define('TRAITE_BANCAIRE','Bank Draft');
define('MANDAT_POSTAL','Money order');
define('CONTRE_REMBOURSEMENT','Cash on delivery');
define('PAIEMENT_AVEC_CO','Cash on delivery payment');
define('VIREMENT_BANCAIRE','bank transfer');
define('MODE_DE_PAIEMENT','Select Payment mode');
define('VOUS_AVEZ_CHOISI',"After payment confirmation, an email will be send to");
define('VOUS_AVEZ_CHOISI2',"Please check your email in order to follow your purchase.<br><br>&bull;&nbsp;<i>Hit the button below to start the payment.</i>");
define('VOUS_AVEZ_CHOISIA',"After your payment confirmation mode, your order will be registered and an email will be send to");
define('VOUS_AVEZ_CHOISI2A',"Please check your email in order to follow your purchase.<br><br>&bull;&nbsp;<i>Hit the following button to confirm your payment mode.</i>");
// page confirm
define('CONFIRMATION_DE_PAIEMENT','Payment confirmation');
define('VOTRE_COMMANDE_EST_DEJA_ENREGISTREE',"Your purchase is already recorded.<br><br>
       - To select another payment, click <a href='payment.php'><b>HERE</b></a>.<br>
       - To modify your order please contact us by <a href=\"mailto:$mailOrder\">email</a> as soon as possible.<br>
       To identify your payment and your order, do not forget to send your <b>NIC</b> with your payment.<br>");
define('RETOUR_BOUTIQUE','Back to the store');
define('UN_EMAIL_A_ETE_ENVOYE1',"An email has been sent to");
define('UN_EMAIL_A_ETE_ENVOYE2',"You have selected payment by");
define('VOTRE_COMMANDE_A_ETE_ENREGISTREE',"Your order has been registered.<br>As soon as payment reception your purchase will be shipped.");
define('VOTRE_COMMANDE_A_ETE_ENREGISTREE_CONTRE',"Your order has been registered.<br>As soon as your payement confirmation on your customer interface, your purchase will be shipped.");

define('AFIN_D_IDENTIFIER_VOTRE_COMMANDE',"To identify your payment and purchase, do not forget to send us your NIC to the back of the cheque or join a print of this email.");
define('AFIN_D_IDENTIFIER_VOTRE_COMMANDE_TRAITE',"To identify your payment and purchase, do not forget to send us your NIC and purchase number or join a copy of this email.");
define('POUR_TOUTE_MODIFICATION',"If you want to modify your order, please contact us as soon as possible to $mailOrder with your NIC.\r\n");                           
define('AFIN_D_IDENTIFIER_VOTRE_COMMANDE_MANDAT',"Do not forget to join your NIC with your money order.<br>Expenses relating to the payment are to your charge.");
define('AFIN_D_IDENTIFIER_VOTRE_COMMANDE_WESTERN',"
  Send money to: <b>".strtoupper($western)."</b><br>
  <b>Important:</b><br> 
  In order to $western can withdraw the required amount, please send us by email to <b>$mailOrder</b> the following informations:<br>
  1 - The numero <b>MTCN</b> (10 digits).<br>
  2 - <b>Complete name and firstname</b> of the person who has sent the money such as writing on the Western Union sending form.<br>
  3 - <b>City and country</b> from where the money has been sent.<br>
  4 - All necessaries informations to withdraw the required amount.<br>
  Expenses relating to the payment are to your charge.");
define('AUSSITOT_CONFIRMATION_DU_PAIEMENT','As soon as payment confirmation, your purchase will be shipped.');
define('OUBLIEZ_PAS_DE_DEMANDER',"Do not forget to ask to your bank to join your NIC as reference with the bank transfer.");
define('FAITES_NOUS_PARVENIR_PAR_EMAIL',"");
define('TELEPHONE','Phone number');
define('DATE','Date');
define('VOUS_VENEZ_DE_FAIRE_UNE_COMMANDE','You have made an order and you have selected payment by');
define('POUR_SUIVRE_VOTRE_COMMANDE_IDENTIFIEZ_VOUS',"Once your purchase payed, your customer interface will be available from http://".$www2.$domaineFull." by login into \"Your Account\" with your Client Number.");
define('VOTRE_COMMANDE_A_ETE_ENREGISTREE_MAIL','Your order is registered.');
define('POUR_SUIVRE_VOTRE_COMMANDE','To follow up your order and find our bank or postal informations, go to your customer interface.');
define('RAPPEL','IMPORTANT RECALL');
define('NUMERO_DE_CLIENT','Client number');
define('INTERFACE_DE_SUIVIT_CLIENT','Customer interface');
define('POUR_TOUTE_INFORMATION','For all information, do not hesitate to contact us');
define('LE_SERVICE_CLIENT','The customer service.');
define('CODE_REMISE_ACTIVE','Discount code activated!');
define('CODE_REMISE_UTILISE','Discount code already used!');
define('TELEPHONE_DE_CONTACT','Your contact telephone for purchase verification');
define('CONFIRMER_MODE_DE_PAIEMENT','Confirm payment mode');
$titreOrder = $titre_order_2;

// page menu_subscribe
define('ENREGISTRER','Subscribe');
define('ADRESSE_EMAIL_INVALIDE','Invalid email!');
define('COMPTE_NON_ACTIVE','Acount not activated!');
define('USAGER_DEJA_ABONNE','User already subscribed!');
define('ACTIVATION_COMPTE_NEWSLETTER','Newsletter activation account');
define('SUJET','Subject:');
define('EMAIL_DEJA_ENREGISTRE','Email already registered to our Newsletter!');
define('POUR_RECEVOIR_LA_LETTRE',' To receive our newsletter, your account must be activated.');
define('POUR_RECEVOIR_LA_LETTRE2','Your account has been activated and you are will receive our Newsletter.');
define('A_L_ADRESSE_CI_DESSOUS','To the bottom url, you can activate or unsubscribe your account.');
define('A_L_ADRESSE_CI_DESSOUS2','Fowards the URL below, you will be able to remove your account if you want to stop receiving our Newsletter.');
define('VOTRE_NUMERO_ACTIVATION','Your activation number');
define('VEUILLEZ_ENTRER_UN_EMAIL','Enter an email!');
define('VEUILLEZ_VERIFIER_VOTRE_EMAIL','Check your email!');
define('MES_PRODUITS','My favorite items');
define('VEUILLEZ_SAISIR','Please enter your telephone number!');
define('VOTRE_COMMANDE_EST_ENREGISTREE_ET','Your order has been registered and your payment mode has been confirmed. Thank you.');
DEFINE("MOT_DE_PASSE_OUBLIE","Password forgotten, click <a href='wachtwoord_vergeten.php' target='blank'>HERE</a>.");
DEFINE("RECUPERER_MOT_DE_PASSE","Recover password");
DEFINE("NO_MOT_DE_PASSE","No Client Number for this email address!");
DEFINE("MOT_DE_PASSE_ENVOYE","An email has been sent to");
//Menu identifiez-vous
define('FERMER_LE_COMPTE','Close your account');
define('VOUS_ETES_IDENTIFIE','Your are identified.');
define('IDENTIFIEZ_VOUS','My Account');

// Page mijn_account.php
define('YOUR_ACCOUNT_NOTE','1 - If your next ET purchase is less than <b>');
define('YOUR_ACCOUNT_NOTE_2',$symbolDevise.'</b>, the discount will be applied for the amount of the purchase.<br> 
       2 - The points not used will be deferred to your next purchase.<br>
			 3 - The discount does not be applied on shipping expenses.<br>
			 4 - To applying to the discount, keep open your account.');
define('VOUS_VENEZ_DE_FERMER_VOTRE_COMPTE','Your account is now closed !');
define('AUCUNE_COMMANDE','Client Number and/or Email Address not valid !');
define('AUCUNE_COMMANDE_VIDE','Enter your Client Number !');
define('NOM_DE_CADDIE_UTILISE','<b>Cart Name already used!</b><br>Start again.');
define('VOTRE_CADDIE_EST_VIDE','<b>Your cart is empty!</b><br>You must have, at least, 1 item into the cart !');
define('VOUS_SOUHAITE_UNE','wish you a nice day.');
define('VOTRE_NUMERO_CLIENT_EST','Your Client Number is');
define('VOUS_AVEZ_PASSE','You have');
define('COMMANDE','purchases');
define('SUR_ECOM_POUR_UN_MONTANT_DE','on '.$store_name.' for a total of');
define('VOTRE_REMISE','YOUR DISCOUNT');
define('LIRE_NOTE','Read note');
define('VOUS_AVEZ_OBTENU','you have get');
define('POINTS_QUI_VOUS_DONNE_DROIT','points.');
define('DE_REDUCTION_SUR','discount on your next purchase.');
define('POINTS_ACCU','Totals points');
define('POINTS_UT','Used points');
define('POINTS_REST','Points remaining');
define('REMISE_SUR_VOTRE_PROCHAINE_COMMANDE','Discount on your next purchase');
define('VOS_FACTURES','YOUR INVOICES');
define('FACTURE','Invoice');
define('VOS_CADDIES','YOUR CARTS');
define('EN_TANT_QUE_CLIENT','As a registered customer, the carts you have saved are not limited in time.');
define('CLIQUEZ_SUR_LE_CADDIE','Click on the cart below to recover it, remove it or update it.');
define('SET_TO_1','All recovered items quantity will be automaticly set to 1.');
define('NBRE_DE_CADDIE','Saved cart quantity');
define('VOUS_N_AVEZ_AUCUN_CADDIE','You have no registered cart.');
define('ENREGISTRER_UN_NOUVEAU_CADDIE','SAVE A NEW CART');
define('SI_VOUS_N_AVEZ_PAS2',"You have lost your Client Number ?<br>Click ");
// Affiliation
define('AFFILIATION','Affiliation');
define('BANQUE','Bank');
define('AI_LU2','I have read the <a href="infos.php?info=12"><u>conditions</u></a>');
define('DEVENIR_AFF','Signup');
define('CONDITIONS_AFF','Affiliation conditions');
define('ICI','HERE');
define('APRES_VOUS_ETRE','After regitration, an email will be sent to you with your affiliate number. Then paste the link of your choice in your website as ');
define('POUR_ADHERER','To subscribe, read the <a href="infos.php?info=12"> <u>affliation conditions</u></a> and fill out the following form...');
define('REMPLACER','<b><u>IMPORTANT</u></b>: Replace XXXXX by your affiliate number you have received by email.');

if($colorInter=="scss") {$linkIpos="ipos/index.php?lang=2&css=scss";}
if($colorInter=="scss2") {$linkIpos="ipos/index.php?lang=2&css=scss2";}
if($colorInter=="Gris-Grey") {$linkIpos="ipos/index.php?lang=2&css=grey";}
if($colorInter=="Rose-Pink") {$linkIpos="ipos/index.php?lang=2&css=pink";}
if($colorInter=="Noir-Black") {$linkIpos="ipos/index.php?lang=2&css=black";}
if($colorInter=="Jaune-Yellow") {$linkIpos="ipos/index.php?lang=2&css=yellow";}
if($colorInter=="Blanc-White") {$linkIpos="ipos/index.php?lang=2&css=white";}
if($colorInter=="Bleu-Blue") {$linkIpos="ipos/index.php?lang=2&css=blue";}
if($colorInter=="perso") {$linkIpos="ipos/index.php?lang=2&css=perso";}

define('NOUS_REMUNERONS',"We pay you <b>".$affiliateCom."%</b> on the sales generated on <b>".$domaine."</b> by visitors coming from your website.<br>
                            Just insert a <b>link</b>, a <b>banner</b> or <a href=\"".$linkIpos."\" target=\"_blank\"><u>that store</u></a> (through the <b>BoutikOne&reg; POS (Point Of Sale) system</b> on your website.<br>
                        <br>After sending the form below, you will receive an email with your affiliate number and all HTML codes to paste in your website as described ");
define('ENREGISTRER_AU_PROGRAMME',"You have been added into the affiliation program of");
define('VOTRE_NUMERO_AFFILIE_EST',"Your affiliate number is");
define('VOTRE_PASS_EST',"Your password is");
define('UN_LIEN','A link into your website');
define('UNE_IMAGE','An image');
define('NO_IMAGE',"No image");
define('UNE_BANNIERE','A banner');
define('CODE','HTML CODE');
define('A_INCLURE','to include in your website or your email');
define('VOUS_ETES_AFFILIE','YOU ARE AFFILIATED.');
define('VOUS_ETES_PAS_AFFILIE','YOU ARE NOT AFFILIATED.');

define('CHEQUE_PAYABLE','Cheque payable to :');
define('PAYPAL_EMAIL','Paypal account email :');
define('TITULAIRE_DU_COMPTE','Bank account name :');
define('VOUS_RECEVREZ_VOTRE_ARGENT','Receive your money through :');

define('SEUIL_DE_PAIEMENT','Minimum amount');
define('SEUIL_DE_PAIEMENT_A_ETE_DEPASSE', 'The minimum amount has been reached.');
define('CE_MONTANT_VOUS_SERA_ENVOYE','This amount will be sent to you very soon.');
define('NON_ATTEINT','not reached.');
define('COMPTE_AFF','AFFILIATE ACCOUNT');
define('SUR_VOTRE_COMPTE','in your account number');
define('DETAILS_COMPTE','Details');
define('COMMISSION','Commission');
define('PAYE','Payed');
define('MONTANT_HT','Purchase ET');
define('MONTANT_COM','Amount commission');
define('TOTAL_PAYE','Total payed');
define('MONTANT_DU','To pay');
define('EN_DATE_AUCUNE','In date of today, no commission has been recorded on your account.');
define('PLACER_UN_LIEN','Paste the link of your choice to your website or your email shown as indicated');
define('AUCUN_COMPTE_AFF','Your affiliate number or/and your password is not valid !');
define('COMMANDE_MINIMUM','Minimum order');
define('AVANT_LIVRAISON','Before any discount and shipping');
define('VOIR_FACTURE','Display');
define('MES_LIENS','My links');

define('INTERFACEW','Interface');
define('LANGUES','Idiomas');
define('NEWSLETTER','Newsletter');
define('CONVERTISSEUR','Converter');
define('MESSAGE1','Select the color of the interface.');
define('MESSAGE2','Select your language by clicking on a flag below.');
define('MESSAGE3','Converter '.$devise.' -> Your devise.');
define('MESSAGE4','[Your comments here]');
define('MESSAGE5','Go quickly toward the items of your choice.');
define('MESSAGE6','Subscribe to our newsletter Now.<br>You will receive your activation code by entering your email in the field.');
define('MESSAGE7','Your cart');
define('MESSAGE8','You can pay your order online now by entering your estimate number in the field below.');

define('NO_TVA','European VAT Id Number');
define('LAISSER_VIDE','Leave empty if no number');
define('PERMET','Allows to collect your credit card information through a secured SSL server.<br>
                The transmitted data will be processed manually from our credit card payment terminal.');
define('PERMET2','Allows to collect your credit card information through a secured <b>2048 bits</b> SSL server.<br>
                The transmitted data will be processed manually from our credit card payment terminal.');
define('VOUS_AVEZ_CHOISI_LIAISON','You have selected Liaison-SSL to process your payment.<br>
                  <br><u>Your payment will be processed manually from our credit card payment terminal.</u><br><br>
                  As soon as your payment confirmation, an email will be sent to ');
define('VEUILLEZ_EN_PRENDRE_CONNAISSANCE','Please take note of it in order to continue your order.<br>
                  // <i>Click the button below to process the payment.</i>');
define('EN_VENTE','for sell');
define('DISPO','Availability');
define('EN_COMMANDE','Place order!');
define('ARTICLE_EN_COMMANDE','Ordering...');
define('BUY_NOW',"<b>Buy Now !</b><br>... and we will ship it to you when it arrives.");
define('BUYED1',"<b>Item in your cart !</b><br>We will ship it to you when it arrives.");
define('AUTRES_OPTIONS',"<i>(Other options available)</i>");
define('ENVOYER_A_UN_AMI','Envoyer � un ami');
define('ENVOYER_CETTE_UN_AMI','Send this page to your friend');
define('VOTRE_NOM','Your name');
define('VOTRE_EMAIL','Your email');
define('EMAIL_AMI','Email of your friend');
define('MESSAGE_DE','Message from');
define('CET_ARTICLE_EST_SUSCEPTIBLE_DE_VOUS_INTERESSER','This item may interest you.');
define('VOUS_INVITE_A_VOUS_RENDRE','invite you to visit the following link:');
define('LE_MESSAGE_SUIVANT_A_ETE_AJOUTE','The following message has been add:');
define('PAGE_ENVOYE','This page has been sent');
define('DESOLE','Sorry, this item is not available any more.');
define('ABONNE_NEWS','Subscribe to the Newsletter ?');
define('PAIEMENT_SECURISE','Secure Payment');
define('COEUR','Our selection !');
define('POUR_CONNAITRE','<p>Select country if you want to know the <b>exact amount to pay</b>.</p>');
define('SAISISSEZ_ICI','<p>Enter the code of your <b>special discount</b> here.</p>');
define('PLUS_INFOS',"More...");
define('DATE_FIN_PROMO',"Offer expiry date");
define('VENTES_FLASH',"Quick sales");
define('VOTRE_PAIEMENT_A','Your payment has been confirmed.<br>
                            <b>'.$store_company.'</b> thanks you for your order.<br><br>
                            <b>An email has been sent to you</b>.<br>
                            Please read it in order to follow your purchase and get your invoice.');
define('ACTVITE',"Business activity");
define('POSTE',"Job");
define('NO_ORDER',"No payed order has been made yet!");
define('PARTENAIRES','Partners');
define('DOMAINE_ACTIVITY',"Business activity");
define('DEVIS','Estimate');
define('DEMANDE_DEVIS','Ask an estimate');
define('DEVIS_TOP','To get estimate, please fill up the Form below.<br>(* means required information)');
define('DEVIS_BOTTOM',"<b>Important:</b> We will not respond to the uncompleted forms. Thanks to leave your name and your email or your telephone to be able to contact you.");
define('ENVOYER_FORMULAIRE','Send the form');
define('ENREGISTRER_AU_DEVIS',"An have ask an estimate on");
define('VOTRE_NUMERO_DEVIS_EST',"Your estimate Number is");
define('VOTRE_DEMANDE','Your request will be processed as soon as possible.');
define('VOTRE_DEMANDE_EMAIL','Your request will be processed as soon as possible.');
define('REFERENCES','REFERENCES');
define('DATEEXP',"Expiry date");
define('A3',"To");
define('INTRO1',"Madam, Sir,");
define('INTRO2',"We warmly thank for your interest and find below, our proposal of estimate according to your request.");
define('NUMERO_DEVIS',"Estimate number");
define('NO_DEVIS_FOUND',"No estimate found.<br>Try again!");
define('CLOSE_DEVIS',"Back to store");
define('ACTIVER_DEVIS',"Activate estimate");
define('NOS_SELECTIONS',"Our selections");
define('LA_BOUTIQUE',"THE STORE");

define('CHEQUE_CADEAU',"GIFT CERTIFICATE");
define('CHEQUE_CADEAU_MIN',"Gift certificate");
define('ACHETER_C',"BUY A GIFT CERTIFICATE");
define('CONTROLE_CHEQUE',"MY GIFT VOUCHER");
define('FAITE_PLAISIR',"<span class=\"fontrouge\"><b>Get it right everytime !</b></span>
                        <br><br>
                        The gift certificate is an original IDEA GIFT whose you fix the amount freely.<br>
                        The recipient uses it on all the products and the services presented on ".$store_name.", including promotions.<br>
                        The value of the gift certificate will be deduced on the total amount from your purchase.<br><br>
                        <b>If the amount of the order is higher than the value of the gift certificate :</b><br>
                            The totality of the value of your gift certificate will be deduced from the amount of the order. Continue the payment process to pay the balance due.<br>
                        <b>If the amount of the order is equal of the value of the gift certificate :</b><br>
                            The totality of your order is payed through your gisft certificate. Continue the payment process to confirm the order.<br>
                        <b>If the amount of the order is lower than the value of the gift certificate :</b><br>
                            The value of the gift certificate will not be deduced from the amount of the order.<br><br>
                        - The gift certificate have an expiry date of 12 months from date of issue. It's non cumulable, non refundable, non exchangeable. Usable only once in its totality only on http://".$www2.$domaineFull.".<br>
                        - Any discount is applied on gift certificate.<br>
                        - ".$store_company." have no responsability in case of lost of the gift certificate code.<br>
                        - Minimum gift certificate value : <b>".sprintf("%0.2f",$seuilGc)."&nbsp;".$symbolDevise."</b><br>
                        ");
define('ENTRER_LE_MONTANT',"Value");
DEFINE("CHAMPS_VIDE","- Empty field");
DEFINE("NOT_NUMBER","ou not numeric field:");
DEFINE("NUMERO_CHEQUE","Gift certificate number");
define('SAISISSEZ_ICI2','<p>Enter your <b>gift certificate</b> code here in order to deduce its value on the amount of your order.</p>');
define('CADEAU_ACTIVE','Gift certificate activated!');
define('CADEAU_UTILISE','Gift certificate already used!');
define('CADEAU_ERRONE','Gift certificate code not valid !');
define('CADEAU_ERRONE2','Gift certificate code not validate !');
define('CADEAU','The deduction on your order is');
define('MONTANT_PAS_SUFFISANT','<p align="center">The amount of your order is lower than your gift certificate value !</p>');
define('NON_CUMULABLE','<p align="center">Discount codes are not cumulable with gifts certificate.</p>');
define('IS_DESACTIVATE',"Gift certificate desactivated.");
define('DESACTIVATE',"Desactivate the gift certificate code.");
define('DESACTIVATE_COUPON',"Desactivate the discount code");
define('IS_DESACTIVATE_COUPON',"The discount code is desactivated.");
define('VALEUR_MIN',"Minimum value of a gift certificate : ".sprintf("%0.2f",$seuilGc)." ".$symbolDevise);
define('PAS_DE_PRODUITS_DANS_CETTE_CATEGORIE_FLASH',"Flash sales are finished for now!<br><br>Come back to visit us soon...");
define('CONTROLER',"Control");
define('NON_UTILISE',"NOT USED");
define('UTILISE',"USED");
define('EXPIRE',"Expired !");
define('CADEAU_EXPIRE_NON_UTILISE',"This gift certificate is expired and has not been used !");
define('DATE_ACTIVATION',"Date of issue");
define('STATUT',"State");
define('GC_NON_ENREGISTRE',"Gift certificate not registered !<br>Try again.");
define('VOS_DEVIS',"Your estimates");
define('SANS_LIVRAISON',"Select 'NO SHIPPING' if withdrawal in store");
define('SUIVANT',"According to delivery destination");
define('DONT',"Including");
define('AJOUTER_FAVORIS',"Add a Bookmark");
define('POINTS_FIDELITE',"Fidelity Gift");
define('TRAITE',"Processed");
define('VOTRE_PRIX',"Your&nbsp;price");
define('UPDATE',"Update");
define('VOS_INFOS',"YOUR DATAS");
DEFINE("AETEMISAJOUR","has been updated");
DEFINE("CECOMPTE","This account does not exist!");
DEFINE("ENREG","Sign Up");
define('SUIVI_COMMANDE',"Order status");

define('ACHAT_TTC',"taxes included");
define('ACHAT_HT',"ET");
define('ACHAT_ST',"no tax");
define('PAS_INCLU',"The shipping price is not included</b>.<br>It will bee added as soon as the destination will be selected.");
define('PEND_GRAT',"During a limited period, **<b><span class=\"fontrouge\"> FREE SHIPPING </span></b>**");
define('PEND_REM',"During a limited period, **<b><span class=\"fontrouge\"> DISCOUNT </span></b>** of");
define("LIV", "Shipping");
define("CONF", "Confirmation");
define("CLIQUER_SUR", "Click on the URL below to see the HTML code to paste on your web site");
define("PREM", "First purchase on");
define("IDVOUS", "LOG IN");


define("EMAIL_ENR", "<b>The Email below is already registered !</b>");
define("TVA_ENR", "<b>European VAT Id Number already registered !</b>");
define("VOS_INFOS_ONT_ETE_ENVOYE", "<b>Your account has been create successfuly!</b><br><br>Your account datas have been sent to");
define("APRES_VERIFICATION", "<b>Your datas has been sent!</b><br>After validation from administrator, you will receive an eamil with your unique acces to your client account.<br>Thank you !");
define("UN_OU_DES_CHAMPS_NE_SONT_PAS_VALIDE", "<b>One or more fields form the form are not valid.</b><br>Please Start again!");
define("CREER_VOTRE_COMPTE", "CREATE YOUR ACCOUNT");
define("DEJA_CLIENT", "I am a returning customer....");
define("FIRST_ORDER", "<b>Take some minutes to create your account.</b><br><br>
                      Opening an account, you can :<br>
                      &bull;&nbsp;Do your next purchases in some clicks.<br>
                      &bull;&nbsp;Follow the evolution and the historic of your orders/estimates.<br>
                      &bull;&nbsp;Manage your carts.<span style='FONT-SIZE:8px;'><sup>1</sup></span><br>
                      &bull;&nbsp;Recover/Modify/Pay your orders not payed.<br>
                      &bull;&nbsp;Have exclusive offers.<span style='FONT-SIZE:8px;'><sup>2</sup></span><br>
                      &bull;&nbsp;Subscribe/unsubscribe to the newsletter.<br>
                      &bull;&nbsp;Modify your information.");
define("FIRST_ORDER_NOTE", "<i>(1) Save and recover unlimited cart for unlimited time.<br>
                  (2) Fidelity points, individual discount.</i>");
define("NOUVEAUX_ACCES", "Please here is your new access to log in your account on");

DEFINE("ACTIVATION_COMPTE_PRO","CLIENT ACCOUNT ACTIVATION");
DEFINE("COMPTE_ACTIVE","Your account has been activated on");
DEFINE("MERCI","Thank you.");
DEFINE("RECUPERER_NO_CLIENT","Client Number recover");
DEFINE("NICO","Order Id");
define("VOUS_DEVEZ_VOUS_IDENTIFIER", "You must now identify you before processing the payment.");
define("DEPUIS", "Since");
define("HORS_LIV", "net of shipping");
define("NEWS_OK", "The newsletter has been updated");
define("DESTINATION", "Destination");
define("POIDS_MAX_DEPASSE", "The maximum weight of the order is passed.");
define("EXPED_IMPOSSIBLE", "No shipping toward this destination!");
define("COO_PRO", "Professionals datas");
define("COO_PERSO", "Personals datas");
define("CLIK_ICI", "Click HERE to go to your account.");
define("CODE_NOT_VALID", "Anti-Spam Code not valid !");
define("CODE_ILLISIBLE", "Reload a new code");
define("RECOPIER", "Write the Anti-Spam Code below");
define("CODE_ANTISPAM", "Anti-Spam Code");
define("SITEMAP", "Sitemap");
define("EN_ATTENTE", "Pending orders...");
define("NO_ORDER_NADA", "No order has been made.");
define("PAKING_COST", "Packing Cost");
define("A_ETE_SUPPRIME", "has been deleted");
define("QUI_SOMMES_NOUS", "About us");
define("ACHAT_EXPRESS", "Express Buy");
define("PAIEMENT_DIRECT", "Direct Payment");
define("VOTRE_COM", "Your Commission");
define('OFFERT','Free');
define('EXTRA','EXTRA...');
define('SUP_FID',"By removing this discount, you can cumulate your fidelity Points.<br>
The amount of this discount will be added to the fidelity Points of your current order and will be deferred on your next order.<br><br>
---<br>
".$domaine." Team");
define('ACTIVE_REMISE','Activate Fidelity Points discount');
define('DESACTIVE_REMISE','Desactivate Fidelity Points discount');
define('IPADRESS','Your IP Address');
define('SUIVANTTT','Next');
define('PRECEDENT','Previous');

define('DIFFUSEZ_CONTENU','RSS Feeds');
define('AJOUTE_BOUT','New items added in the shop');
define('NO_RSS','No RSS feed found.');
define('RSS_TEXT',"<b>RSS</b> is a Internet technology which enables you to keep in touch with our shop remotely and be informed about our last news.<br>");
define('RSS_TEXT2',"By subscribing freely with a RSS Feed as those above, you will receive information in real time in your RSS Feed Reader without connecting in our shop.<br>
   <br>
   In the list above, select a RSS Feed, copy URL and paste it into the software of your choice.<br>
   Among the applications known as RSS Reader, we recommend you <a href='http://www.netvibes.com/' target='_blank'><u>Netvibes</u></a> or <a href='http://www.google.com/reader' target='_blank'><u>Google Reader</u></a>.<br>
   <br>
   &bull;&nbsp;<b>Online RSS Reader (accessible via any computer)</b> :<br>
   - <a href='http://www.netvibes.com/' target='_blank'><u>NetVibes</u></a><br>
   - <a href='http://www.webwag.com/' target='_blank'><u>WebWag</u></a><br>
   - <a href='http://www.bloglines.com/' target='_blank'><u>Bloglines</u></a><br>
   - <a href='http://www.google.com/reader' target='_blank'><u>Google Reader</u></a><br>
   - <a href='http://fr.my.yahoo.com/' target='_blank'><u>MyYahoo</u></a><br>
   etc...<br><br>
   &bull;&nbsp;<b>RSS Reader to intall in your computer</b>:<br> 
   - <a href='http://www.geste.fr/alertinfo/home.html' target='_blank'><u>AlertInfo</u></a><br>
   - <a href='http://www.feedreader.com' target='_blank'><u>FeedReader</u></a><br>
<br>
   <br>
   <i>NOTE : For the use of these RSS Readers above, please refer you to the documentation or/and the online help of selected software.</i>
   <br><br>");
define('NO_DOC','No document found !');
define('ACTU','Store News');
define('ACTU_MAJ','OUR STORE NEWS');
define('ACTUS','News');
DEFINE("CHEQUES_CADEAUX","Gift Certificate");
define('RECHERCHE_AVANCEE','Advanced&nbsp;Search');
define("TOUS_LES_MOTS", "All words");
define("NIMPORTE_QUEL_MOT", "Any word");
define("PHRASE_EXACTE", "Exact sentence");
define('PAGE400_TITRE','Page not found !');
define('PAGE404',"<p align='left'>
<b>Please try the following :</b><br><br>
&bull; <b>If you are obsessive-compulsive</b>, please check the URL repeatedly.<br><br>
&bull; <b>If you are co-dependent</b>, please ask someone to check the URL for you.<br><br>
&bull; <b>If you are paranoid-delusional</b>, we know who you are and what you want.  Just stay online until we can trace your computer.<br><br>
&bull; <b>If you are schizophrenic</b>, listen carefully and a little voice will tell you the correct URL.<br><br>
&bull; <b>If you are manic-depressive</b>, it doesn't matter what URL you pick.  No one cares, and no one will give you the correct file.<br><br>
If you do not suffer any of the above symptoms, press any link to go to a new page.");
define('OUT_OF_STOCK','Out of stock');
define('ITEMS_OUT_OF_STOCK','Item out of stock');
define('NO_ITEM_FOUND','No product found');
define('PREMIERE_PAGE','First page');
define('DERNIERE_PAGE','Last page');
define('VOIR_CERTIFICAT','See the FIA-NET certificate');
define('INFORMATIONS','Informations');
define('DIVERS','Miscellaneous');
define('NOTE','Note');
define('REMBOURSE','Refunded');
define('PAGE_DE','of');
define('CLIQUEZ_SUR_LE_LOGO','&bull;&nbsp;Click the logo below to start your payment.');
define('D_ACHAT','of purchase');
define('COMMANDE_REMBOURSE','Order refunded');
define('RECUP_COMMANDE_PANIER','Recover/Modify this order into the cart');
define('DIRECT_PAYMENT','Pay this order');
define('RESAISIR_EMAIL','Enter again your<br>E-mail address');
define('VERIF_EMAIL','Check your E-mail address');
define('PAIEMENT_CARTE','Pay by credit/debit card');
define('PAIEMENT_AUTRE','Other Payment');
define('FINANCEMENT','Financing of your payment');
define('FIANCEMENT_A_PARTIR_DE','Financing is available for purchases greater than');
define('VOTRE_COMMANDE_EST_DE','The amount of your order is');
define('ART_AFFIL',"AFFILIATES ITEMS");
define('AUTRE_ADRESSE_DE_LIVRAISON','Other shipping address');
define('ETES_SUR_DE_SUPPRIMER_COMMANDE',"Are you sure you want to delete the order");
define("LA_COMMANDE", "The order");
define("A_ETE_SUPPRIMEE", "has been deleted!");
define("SUPPRIMER_CETTE_COMMANDE", "Delete this order");
define("PENDANT_X_JOURS", "During <b>".$pendingOrder." days</b> after the date of your order, you can pay, delete, recover and\or modify your order. Passed this delay, the order will be deleted.");
define("COMMANDE_EFFECTUEE_IL_Y_A", "Order made :");
define("COMMANDE_SUPPRIMEE", "Order deleted");
define("COMMANDE_SUPPRIMEE_PAR", "Order deleted by the customer through his Custommer Account");
define("COMPTE_CLIENT", "Customer Account");
define("EMAIL_CLIENT", "Customer Email");
define('TOUTES_CAT2','By categories');
define('EXP','Shipped');
define('LES_PRIX_FIGURANT','<b><u>IMPORTANT</u></b>:<br>The prices displayed on this shop are modifiable without advance notice and are not a commitment from');
define('CATALOG_CONTENTS','Catalog contents on');
DEFINE("VOUS_AVEZ_ACHETEEEE","You have bought a gift certificate on");
define('VOUS_REMERCIE',"thanks you for your purchase.");
define('CI_DESSOUS',"Below get informations about your Gift Certificate.");
define('MONTANT_DE',"Gift Certificate Amount");
define('URL_DE',"Gift Certificate URL for printing");
define('DE_REDUCTION','saved');
define('VOTRE_REMISE_CLIENT','Your discount as client on all products on');
define("COMMANDE_EFFECTUEE", "Order made");
define('CETTE_COMMANDE','This order');
define('A_DEJA_ETE_TRAITEE','has been already handled by Moneybookers.<br>Please select another method of payment<br><b>OR</b><br>Add your order into the cart and make your payment through the usual process.');
define('A_TITRE_INDICATF','Approximate price');
define('MB_EST_UN_COMPTE_BANCAIRE','MoneyBookers is a virtual bank account which allows you receive payments by email <u>OR</u> by credit card.<br>The payment with MoneyBookers is full secured.');
define('VOTRE_PAIEMENT_REFUSE',"Your payment has been refused by the secured server.<br>
                              For all question about the reasons of this refusal, please verify by your bank.<br>
                              Don't hesitate to visit us again or pay us through another method of payment.<br>
                            <b>".$store_company."</b> thank you for your interest.<br>");
define('PAIEMENT_EMAIL','Pay by Moneybookers e-wallet');
define('PAIEMENT_DE_CETTE_COMMANDE','Pay this purchase');
define('MODE_DE_LIVRAISON','Shipping provider');
define('VEUILLEZ_CHOISIR_MODE_DE_LIVRAISON','Please select a shipping provider');
define('SELECTIONNER_CE_MODE_LIVRAISON','Select this shipping provider');
define('PARAMS_LIVRAISON_NON_DEFINIS','Shipping provider Parameters not defined.');
define('AVANT_REMISE','before discount');
define('LEAVE_CHAMPS_EMPTY','Leave the field empty to validate the form');
define("CHAMP_NOT_EMPY", "The field must be empty !");
define('NON_VALIDE','not valid');
define('EN_ATTENTE_DE_VALIDATION','pending of validation');
define('LA_DETAXE_DE_VOTRE_COMMANDE_EST_SOUMISE_A_LA_VERIFICATION','The tax calculation of your order is submitted to your VAT EU Id number validation by our accounting service.');
define('VOUS_AVEZ_DESACTIVE_JS',"You have disactivated Javascript on your navigator.");
define('VOUS_POUVEZ_POURSUIVRE_MAIS',"<b><u>You can continue your purchases</u></b> but some actions won't be functional.");
define('CLIQUEZ_ICI_POUR_ACTIVER_JS',"Click here to activate javascript on your navigator.");
define('MODIFIER','Modify');
define('SAVE_THIS_ORDER','Update this order');
define('COMMANDE_MODIFIEE','This order has been modified');
define('COMPTE_CLIENT_OUVERT_COMMANDE_RECUPEREE',"Client account and order loaded");
define('VEUILLEZ_MODIFIER_LA_COMMANDE_PUIS_CLIQUEZ_CADDIE',"Please modify the current order then click <a href='berekenen.php'><b><span style='color:#FFFFFF'>HERE</span></b></a> to update the order");
define('CLIQUEZ_ICI_POUR_ANNULER',"Click here to cancel this operation.");
define('CLIQUEZ_BOUTON_UPDATE',"Click on the button '<b>Update this order</b>' to update the order");
define('AUCUNE_LIVRAISON_DANS_CE_PAYS',"No shipping to the selected country");
define('POIDS_TOTAL_DEPASSE_NOS_CAPACITES',"The total weight of your order is over our shipping capacities.");

define('DELAI_EXPEDITION',"Shipping time limits");
define('ENTRE',"Within");
define('ET',"and");
define('JOURS_OUVRES',"working day(s).");
define('DATE_LIVRAISON',"Delivery date");
define('ESTIMATION_FIN_COMMANDE',"Estimate at the end of your purchase.");
define('EN_TELECHARGEMENT_A_LA_CONFIRMATION_DU_PAIEMENT',"On payment confirmation.");
define('SOUS',"Under");
define('DELAI_LIVRAISON',"Delivery time limits");
define('ESTIMATION',"Estimation");
define('ENTRE_LE',"Between&nbsp;");
define('ET_LE',"and&nbsp;");
define('INFOS_LIVRAISON',"INFOS DELIVERY");
define("COO", "Contact informations");
define("AJOUTER_COMMANDE_A_LA_BDD", "Add this order to database");
define("AJOUTER_COMMANDE", "Add order");
define("LAST_VIEWED", "Last products viewed !");
define("TOUT_SUPPRIMER", "Delete all");
define("GARANTIE", "Guarantee");
define("VOIR_ALL_ACTUS", "To see all news from the shop");
define("LES", "THE");
define('CLIQUEZ_SUR_LE_LOGO2','&nbsp;Click the logo below to start the payment process.');
define("ETAT_COMMANDE", "Order Statement");
define("READY", "Ready");
define("EN_PREPARATION", "In process");
define("VOTRE_LIEN_SUR", "Or send/email the link below to your friends");
define('UN_LIEN_DANS_EMAIL','A link sent by email');
define('COMPTE_A_JOUR','Acount has been updated.');

define('VOUS_REMUNERE_A_HAUTEUR_DE','give you back');
define('SUR_LES_VENTES_GENEREES','on sales done by customers you have sent to us.');
define('CADDIE_HTM',"<p>
					How to use your shopping cart<br>
					</p>
					<table width='100%' border='0' cellpadding='0' cellspacing='0'>
					<tr>
					<td><img src='im/lang2/use_caddie.gif'></td>
					<td valign='top'>
					<ul>
					<li>To add items in your cart, browse our shop until the item you wish to add. Enter the quantity then clic on the following button:<br><img src='im/cart_add.png'><br><br></li>
					<li>To add, add or remove items from your cart by clicking the following buttons : <img src='im/_plus.gif' width='5' height='5'>|<img src='im/_moins.gif' width='5' height='5'>|<img src='im/_quit.gif' width='5' height='5'><br><br></li>
					<li>At any time, you can go in &quot;My cart&quot; to modify or see your purchase details.<br><br></li>
					<li>Clic on &quot;Empty cart&quot; to remove all items from your cart.<br><br></li>
					<li>By clicking on &quot;Save/Get cart&quot;, you can save your cart and recover it later.<br><br></li>
					<li>Once your cart complete, go into &quot;My cart&quot; and clic &quot;Payment&quot; to start the payment process.</li>
					</ul>
					</td>
					</tr>
					</table>");
define('COMMANDER_NO','Payments desactivated.');
define("CE_COMPTE_EXISTE_DEJA", "This customer account already exists!");
define("VEUILLEZ_RECOMMENCER", "Please start again");
define("MODIFICATION_EFFECTUEE", "Account modified.");
define("VOTRE_EMAIL_EST", "Your email is");
define("CAR_MAX", "15 caracters max");
define("MODIFIER_COMPTE_CLIENT", "Modufy customer account number");
DEFINE("FAX","Fax");
DEFINE("NEW_NUMERO","Your new customer account number");
DEFINE("QUANTITY","Quantity");
DEFINE("PRODUIT_A_PRIX_DEGRESSIF","Discount on quantity");
DEFINE("PRIX__UNITAIRE","Unit price");
DEFINE("EXPEDI"," Shipping ");
DEFINE("DECLINAISON_EPUISEE","This product attribute is out of stock");
DEFINE("DECLINAISON_NON_REPERTORIEE","This product attribute is not listed. Please do another selection.");
DEFINE("VOIR_STOCK","See all stock");
DEFINE("CACHER_STOCK","Hide stock");
DEFINE("VIE_STOCK_DES","Stock");
DEFINE("RECPERS","Your records");
DEFINE("ECOTS","Eco-tax");
DEFINE("SEFRIENNOM","Your name");
DEFINE("IPOST","Sell our products trough your website with the IPOS system  - Internet Point of sale");
define('COMMANDEMAIL','Your order');
DEFINE("NICEMAIL","NIC number - order number");
DEFINE("ETOUM","and - or");
DEFINE("PAYALERT","Select a payment");
DEFINE("PAIEMENTOGONE","Pay with Ogone");
DEFINE("PAIEMENTPAYNL","Pay with Pay.nl");
define('AUSSITOT_CONFIRMATION_DU_PAIEMENTA','Your order will be shipped soon as possible.');
define('POUR_SUIVRE_VOTRE_COMMANDEA','You can follow the status of your order into you client interface.');
DEFINE("MODELIVRI","Delivery");
?>
